### ISSUE TITLE
Skywalking container failing to start with SSL enabled. 

### ISSUE THREAD

**Issue by javamak** [sourceplusplus/live-platform#290]
Below is the stacktrace. 
https://gist.github.com/javamak/40c3293d8108b2dcdac5c78800427036 

When below environment variables set to false it works fine. 
_SW_RECEIVER_GRPC_SSL_ENABLED
SW_CORE_GRPC_SSL_ENABLED_

**Comment by BFergerson** [comment]
Adding stack trace from gist to issue:
```
10 22:27:48,563 - org.apache.skywalking.oap.server.library.module.ModuleDefine -2000 [main] INFO  [] - Prepare the default provider in core module.

2022-01-10 22:27:50,387 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -3824 [main] ERROR [] - Illegal base64 character d

java.lang.IllegalArgumentException: Illegal base64 character d

at java.util.Base64$Decoder.decode0(Unknown Source) ~[?:?]

at java.util.Base64$Decoder.decode(Unknown Source) ~[?:?]

at java.util.Base64$Decoder.decode(Unknown Source) ~[?:?]

at org.apache.skywalking.oap.server.library.server.ssl.PrivateKeyUtil.loadDecryptionKey(PrivateKeyUtil.java:50) ~[library-server-8.9.1.jar:8.9.1]

at org.apache.skywalking.oap.server.library.server.grpc.ssl.DynamicSslContext.updateContext(DynamicSslContext.java:68) ~[library-server-8.9.1.jar:8.9.1]

at org.apache.skywalking.oap.server.library.server.ssl.AbstractSslContext.<init>(AbstractSslContext.java:38) ~[library-server-8.9.1.jar:8.9.1]

at org.apache.skywalking.oap.server.library.server.grpc.ssl.DynamicSslContext.<init>(DynamicSslContext.java:50) ~[library-server-8.9.1.jar:8.9.1]

at org.apache.skywalking.oap.server.library.server.grpc.ssl.DynamicSslContext.forServer(DynamicSslContext.java:42) ~[library-server-8.9.1.jar:8.9.1]

at org.apache.skywalking.oap.server.library.server.grpc.GRPCServer.initialize(GRPCServer.java:116) ~[library-server-8.9.1.jar:8.9.1]

at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:218) ~[server-core-8.9.1.jar:8.9.1]

at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:96) ~[library-module-8.9.1.jar:8.9.1]

at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:46) ~[library-module-8.9.1.jar:8.9.1]

at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:44) [server-starter-8.9.1.jar:8.9.1]

at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-8.9.1.jar:8.9.1]
```
