### ISSUE TITLE
Jetbrains plugin timing out

### ISSUE THREAD

**Issue by MrMineO5** [sourceplusplus/live-platform#421]
I'm not sure if I set the platform up wrong, but I am getting errors in my IntelliJ logs:

```
2022-07-20 18:19:48,634 [ 495191]   INFO - STDERR - (TIMEOUT,-1) Timed out after waiting 30000(ms) for a reply. address: __vertx.reply.334, repliedAddress: monitor.skywalking.service.currentService
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:76)
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:24)
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:899)
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:866)
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:56)
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:23)
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53)
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:23)
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:889)
2022-07-20 18:19:48,635 [ 495192]   INFO - STDERR - 	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
2022-07-20 18:19:48,636 [ 495193]   INFO - STDERR - 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
2022-07-20 18:19:48,636 [ 495193]   INFO - STDERR - 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
2022-07-20 18:19:48,636 [ 495193]   INFO - STDERR - 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
2022-07-20 18:19:48,636 [ 495193]   INFO - STDERR - 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
2022-07-20 18:19:48,636 [ 495193]   INFO - STDERR - 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
2022-07-20 18:19:48,636 [ 495193]   INFO - STDERR - 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-07-20 18:19:48,636 [ 495193]   INFO - STDERR - 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-07-20 18:19:48,636 [ 495193]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:829)
```

I think I have the platform set up correctly because before these errors start, the plugin initializes successfully:
```
2022-07-20 18:17:43,046 [ 369603]   INFO - STDOUT - 18:17:43.046 INFO  s.j.s.SourceMarkerPlugin - Discovering available services
2022-07-20 18:17:43,078 [ 369635]   INFO - STDOUT - 18:17:43.078 INFO  s.j.s.SourceMarkerPlugin - Live service available
2022-07-20 18:17:43,079 [ 369636]   INFO - STDOUT - 18:17:43.079 INFO  s.j.s.SourceMarkerPlugin - Live instruments available
2022-07-20 18:17:43,084 [ 369641]   INFO - STDOUT - 18:17:43.084 INFO  s.j.m.SourceMarker - Adding global source mark event listener: spp.jetbrains.sourcemarker.status.LiveStatusManager@6e5e403c
2022-07-20 18:17:43,092 [ 369649]   INFO - STDOUT - 18:17:43.091 INFO  s.j.s.SourceMarkerPlugin - Live views available
2022-07-20 18:17:43,092 [ 369649]   INFO - STDOUT - 18:17:43.092 DEBUG s.j.m.s.SkywalkingMonitor - Setting up Apache SkyWalking monitor
2022-07-20 18:17:43,093 [ 369650]   INFO - STDOUT - 18:17:43.093 DEBUG s.j.m.s.SkywalkingMonitor - Apache SkyWalking server: http://localhost:12800/graphql
2022-07-20 18:17:43,117 [ 369674]   INFO - STDOUT - 18:17:43.116 INFO  s.j.m.s.SkywalkingClient - Registering Apache SkyWalking codecs
2022-07-20 18:17:43,118 [ 369675]   INFO - STDOUT - 18:17:43.118 INFO  s.j.m.s.SkywalkingMonitor - Successfully setup Apache SkyWalking monitor
2022-07-20 18:17:43,119 [ 369676]   INFO - STDOUT - 18:17:43.118 INFO  s.j.s.p.PortalController - Initializing portal
2022-07-20 18:17:43,119 [ 369676]   INFO - STDOUT - 18:17:43.119 INFO  s.j.s.p.PortalController - Initializing portal server
2022-07-20 18:17:43,125 [ 369682]   INFO - STDOUT - 18:17:43.124 INFO  s.j.s.p.PortalController - Portal server initialized
2022-07-20 18:17:43,125 [ 369682]   INFO - STDOUT - 18:17:43.125 INFO  s.j.m.SourceMarker - Adding global source mark event listener: spp.jetbrains.sourcemarker.portal.PortalController$$Lambda$4783/0x00000001030c3440@63159e7c
2022-07-20 18:17:43,125 [ 369682]   INFO - STDOUT - 18:17:43.125 INFO  s.j.s.p.PortalController - Portal initialized
2022-07-20 18:17:43,134 [ 369691]   INFO - STDOUT - 18:17:43.134 INFO  s.j.s.s.LiveInstrumentManager - Found 0 active live status bars
```

**Comment by MrMineO5** [comment]
I had a lot of difficulty actually finding this error, since all exceptions in coroutines end up throwing a fatal exception because the CoroutineExceptionHandlerImplKt class cannot be found [IDEA-277886](https://youtrack.jetbrains.com/issue/IDEA-277886/javalangNoClassDefFoundError-Could-not-initialize-class-kotlinxcoroutinesCoroutineExceptionHandlerImplKt-when-exception-thrown)](https://youtrack.jetbrains.com/issue/IDEA-277886/javalangNoClassDefFoundError-Could-not-initialize-class-kotlinxcoroutinesCoroutineExceptionHandlerImplKt-when-exception-thrown). I ended up creating that class myself just to debug what the root cause of the issue is.

**Comment by BFergerson** [comment]
Apologies for the trouble. I've run into this one before and I have an idea on how to trigger it. I'll work on fixing it soon.
I'm pretty sure you can safely ignore it for now. Worst case scenario, close the file and open it again if something isn't working.

If you're able to recreate it consistently, please let me know.

**Comment by BFergerson** [comment]
https://github.com/sourceplusplus/interface-jetbrains/pull/785 created for the timeout issue and https://github.com/sourceplusplus/interface-jetbrains/commit/fcae8c678c41b6404a8a0e10d7fc76cce045cb6a is a temporary fix for the NPE.

Just saw the third issue. I'm aware of that issue happening. I'll leave this issue open until I catch it.
