### ISSUE TITLE
Platform error after getting redirected from login

### ISSUE THREAD

**Issue by MrMineO5** [sourceplusplus/live-platform#489]
When logging in on the http port I got redirected to /auth with the body "Internal server error", this issue did not occur again after reloading the page, so it may only happen sometimes. See the stacktrace below.

```java
2022-07-26 17:31:36,045 - spp.platform.core.SourcePlatform -121844 [vert.x-eventloop-thread-7] ERROR [] - Failed request: /auth
java.lang.IllegalStateException: Request has already been read
        at io.vertx.core.http.impl.Http1xServerRequest.checkEnded(Http1xServerRequest.java:651) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.core.http.impl.Http1xServerRequest.handler(Http1xServerRequest.java:292) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:104) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:128) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:46) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1267) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:126) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$handle$6(SessionHandlerImpl.java:301) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262) ~[spp-platform-core-0.5.5.jar:?]
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[spp-platform-core-0.5.5.jar:?]
        at spp.platform.dependencies.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [spp-platform-core-0.5.5.jar:?]
        at spp.platform.dependencies.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [spp-platform-core-0.5.5.jar:?]
        at spp.platform.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [spp-platform-core-0.5.5.jar:?]
        at spp.platform.dependencies.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [spp-platform-core-0.5.5.jar:?]
        at spp.platform.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [spp-platform-core-0.5.5.jar:?]
        at spp.platform.dependencies.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [spp-platform-core-0.5.5.jar:?]
        at spp.platform.dependencies.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [spp-platform-core-0.5.5.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by MrMineO5** [comment]
Edit: This error is happening on many endpoints

**Comment by BFergerson** [comment]
Sorry for the delay. My computer completely died on me.

Can you provide more information on how to recreate this issue?

**Comment by MrMineO5** [comment]
The issue was happening on the docker image, not sure if it is still present, it did not happen when creating the container using assembleUp

**Comment by MrMineO5** [comment]
The issue is no longer occurring in the latest docker image
