### ISSUE TITLE
JDK 17 support

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/live-platform#552]
```
Caused by: java.lang.NumberFormatException: For input string: "17-ea"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at spp.probe.SourceProbe.getJvmMajorVersion(SourceProbe.kt:449)
	at spp.probe.SourceProbe.addAgentToClassLoader(SourceProbe.kt:350)
	at spp.probe.SourceProbe.premain(SourceProbe.kt:136)
```

**Comment by MrMineO5** [comment]
I didn't run into this issue on OpenJDK 17, ea appears to be a suffix added in early access versions of the JVM. It should be fine to simply remove -ea from the version name if it is present.
