### ISSUE TITLE
ArtifactSearch.detectRootPackage should use runReadAction

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/live-platform#553]
```
Details: Current thread: Thread[DefaultDispatcher-worker-2,6,main] 524472160
Dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 586048503

java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1056)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:392)
	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:168)
	at com.intellij.psi.NonClasspathClassFinder.lambda$processPackageDirectories$5(NonClasspathClassFinder.java:164)
	at com.intellij.psi.NonClasspathClassFinder.lambda$processDirectories$6(NonClasspathClassFinder.java:178)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:713)
	at com.intellij.psi.NonClasspathClassFinder.processDirectories(NonClasspathClassFinder.java:177)
	at com.intellij.psi.NonClasspathClassFinder.processPackageDirectories(NonClasspathClassFinder.java:163)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.processPackageDirectories(JavaPsiFacadeImpl.java:332)
	at com.intellij.psi.impl.file.PsiPackageImpl.lambda$createCachedDirectories$2(PsiPackageImpl.java:79)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.psi.impl.file.PsiPackageImpl.getAllDirectories(PsiPackageImpl.java:65)
	at com.intellij.psi.impl.file.PsiPackageBase.getDirectories(PsiPackageBase.java:64)
	at com.intellij.psi.impl.file.PsiPackageBase.getDirectories(PsiPackageBase.java:59)
	at spp.jetbrains.marker.jvm.ArtifactSearch.detectRootPackage(ArtifactSearch.kt:64)
	at spp.jetbrains.sourcemarker.SourceMarkerPlugin.init(SourceMarkerPlugin.kt:177)
	at spp.jetbrains.sourcemarker.SourceMarkerPlugin.init$default(SourceMarkerPlugin.kt:139)
	at spp.jetbrains.sourcemarker.stat.SourceStatusServiceImpl$launchPeriodicInit$1.invokeSuspend(SourceStatusServiceImpl.kt:137)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by BFergerson** [comment]
Fixed via https://github.com/sourceplusplus/interface-jetbrains/commit/28bcde1f85998494fbe8e7b4d874a055f3b6e37f
